# Give the execution path of picard and gatk
# You may want to increase the memory available
# to java with
# "java -Xmx50G -jar GenomeAnalysisTK.jar"
gatk_path: "java -jar GenomeAnalysisTK.jar"
picard_path: "java -jar picard.jar"

# Set the working directory (wd)
wd: test


# You must create and populate these directories in your
# working directory (wd) with the starting files.
# Symbolic links should work.
fastq_dir: 0.fastq
refgen_dir: 0.reference_genome_fasta
dbsnp_dir: 0.dbsnp

trimmed_dir: 1.trimmed
sam_dir: 2.sam_dir
read_groups_dir: 3.read_groups
mark_dups_dir: 4.mark_dups
recal_bases_dir: 5.recal_bases
variants_dir: 6.variants_dir
joint_variants_dir: 7.joint_variants_dir


bowtie2_build_threads: 12
bowtie2_map_threads: 6