name: dnavcw
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- bwa=0.7.16=pl5.22.0_0
- cutadapt=1.14=py36_0
- fastqc=0.11.5=1
- htslib=1.5=0
- java-jdk=8.0.92=1
- samtools=1.5=2
- trim-galore=0.4.3=pl5.22.0_1
- xopen=0.1.1=py36_0
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- curl=7.54.1=0
- krb5=1.14.2=0
- libssh2=1.8.0=1
- ncurses=5.9=10
- openssl=1.0.2l=0
- perl=5.22.0.1=0
- pip=9.0.1=py36_0
- python=3.6.2=0
- readline=6.2=0
- setuptools=36.3.0=py36_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.8=3
- pip:
  - awscli==1.11.108
  - botocore==1.5.71
  - colorama==0.3.7
  - jmespath==0.9.3
  - pyasn1==0.2.3
  - rsa==3.4.2
  - s3transfer==0.1.10

